/**
 * @license
 * Copyright 2021 Google LLC
 * SPDX-License-Identifier: BSD-3-Clause
 */

export const tokens = [
  {
    id: 'codeBackground',
    label: 'Background',
    cssProperty: '--playground-code-background',
    defaultValue: '#ffffff',
  },
  {
    id: 'synDefault',
    label: 'Default',
    cssProperty: '--playground-code-default-color',
    cmClass: '.cm-line',
    defaultValue: '#000000',
  },
  {
    id: 'synKeyword',
    label: 'Keyword',
    cssProperty: '--playground-code-keyword-color',
    cmClass: 'tok-keyword',
    defaultValue: '#770088',
  },
  {
    id: 'synAtom',
    label: 'Atom',
    cssProperty: '--playground-code-atom-color',
    cmClass: 'tok-atom',
    defaultValue: '#221199',
  },
  {
    id: 'synNumber',
    label: 'Number',
    cssProperty: '--playground-code-number-color',
    cmClass: 'tok-number',
    defaultValue: '#116644',
  },
  {
    id: 'synBool',
    label: 'Bool',
    cssProperty: '--playground-code-bool-color',
    cmClass: 'tok-bool',
    defaultValue: '#221199',
  },
  {
    id: 'synDef',
    label: 'Def',
    cssProperty: '--playground-code-def-color',
    cmClass: 'tok-definition',
    defaultValue: '#0000ff',
  },
  {
    id: 'synVariable',
    label: 'Variable',
    cssProperty: '--playground-code-variable-color',
    cmClass: 'tok-variableName',
    defaultValue: '#000000',
  },
  {
    id: 'synProperty',
    label: 'Property',
    cssProperty: '--playground-code-property-color',
    cmClass: 'tok-propertyName',
    defaultValue: '#000000',
  },
  {
    id: 'synOperator',
    label: 'Operator',
    cssProperty: '--playground-code-operator-color',
    cmClass: 'tok-operator',
    defaultValue: '#000000',
  },
  {
    id: 'synVariable2',
    label: 'Variable 2',
    cssProperty: '--playground-code-variable-2-color',
    cmClass: 'tok-variableName2',
    defaultValue: '#0055aa',
  },
  {
    id: 'synVariable3',
    label: 'Variable 3',
    cssProperty: '--playground-code-variable-3-color',
    cmClass: 'tok-namespace',
    defaultValue: '#008855',
  },
  {
    id: 'synType',
    label: 'Type',
    cssProperty: '--playground-code-type-color',
    cmClass: 'tok-typeName',
    defaultValue: '#008855',
  },
  {
    id: 'synComment',
    label: 'Comment',
    cssProperty: '--playground-code-comment-color',
    cmClass: 'tok-comment',
    defaultValue: '#aa5500',
  },
  {
    id: 'synString',
    label: 'String',
    cssProperty: '--playground-code-string-color',
    cmClass: 'tok-string',
    defaultValue: '#aa1111',
  },
  {
    id: 'synString2',
    label: 'String 2',
    cssProperty: '--playground-code-string-2-color',
    cmClass: 'tok-string2',
    defaultValue: '#ff5500',
  },
  {
    id: 'synMeta',
    label: 'Meta',
    cssProperty: '--playground-code-meta-color',
    cmClass: 'tok-meta',
    defaultValue: '#555555',
  },
  {
    id: 'synQualifier',
    label: 'Qualifier',
    cssProperty: '--playground-code-qualifier-color',
    cmClass: 'tok-modifier',
    defaultValue: '#555555',
  },
  {
    id: 'synBuiltin',
    label: 'Builtin',
    cssProperty: '--playground-code-builtin-color',
    cmClass: 'tok-labelName',
    defaultValue: '#3300aa',
  },
  {
    id: 'synTag',
    label: 'Tag',
    cssProperty: '--playground-code-tag-color',
    cmClass: 'tok-tagName',
    defaultValue: '#117700',
  },
  {
    id: 'synAttribute',
    label: 'Attribute',
    cssProperty: '--playground-code-attribute-color',
    cmClass: 'tok-attributeName',
    defaultValue: '#0000cc',
  },
  {
    id: 'synCallee',
    label: 'Callee',
    cssProperty: '--playground-code-callee-color',
    cmClass: 'tok-labelName',
    defaultValue: '#000000',
  },
  // TODO(aomarks) local?
] as const;
