name: deploy-demo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15

      # Needed because a recent version of NPM changed SHAs for git
      # dependencies, breaking our package-lock.json files.
      - name: Update NPM
        run: npm i --global npm@^7.8.0

      - name: NPM install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages
        run: |
          cp -r configurator/deploy ..
          git fetch origin gh-pages --depth=1
          git checkout --track origin/gh-pages
          ls -A1 | grep -vx .git | xargs rm -rf
          mv ../deploy/* .
          if [[ -n $(git status -s) ]]
          then
            git config user.name "$GITHUB_ACTOR (bot)"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add -A
            git commit -am "Deploy $GITHUB_SHA"
            git push
          fi
