name: deploy-demo

on:
  push:
    branches:
      - main

jobs:
  deploy-demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm ci
      - run: npm run build

      - name: Deploy to gh-pages
        run: |
          cp -r configurator/deploy ..
          git fetch origin gh-pages --depth=1
          git checkout --track origin/gh-pages
          ls -A1 | grep -vx .git | xargs rm -rf
          mv ../deploy/* .
          if [[ -n $(git status -s) ]]
          then
            git config user.name "$GITHUB_ACTOR (bot)"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add -A
            git commit -am "Deploy $GITHUB_SHA"
            git push
          fi
