name: lint-and-format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - uses: google/wireit@setup-github-actions-caching/v1

      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
