name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm
      - uses: google/wireit@setup-github-actions-caching/v1

      - run: npm ci
      - run: npx playwright install-deps
      - run: npm test
        env:
          WIREIT_FAILURES: continue
