name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm ci
      - run: npx playwright install-deps
      - run: npm run build
      - run: npx wtr
      - run: npx playwright test
